Add beta testing remark and intro to top-level readme
UniversalRobots/Universal_Robots_ROS_Driver pull request #320
Opened 2021-02-23 15:07 UTC by stefanscherzinger

Make sure that users know it's a beta version. Also provide an easy start and show them where to file issues.

Additional things we should add:
- Link to the respective UR forum
- Give users a way of simple (non-issue-tracking) feedback, e.g. with a poll or similar.

2021-02-24 15:19 UTC, urrsk commented
It looks ok

2021-02-24 17:10 UTC, stefanscherzinger commented
Yes, I put this last to be most visible.

2021-02-25 11:21 UTC, urrsk requested changes

2021-02-25 11:21 UTC, urrsk commented on README.md
> +Additionally, please feel free to email further suggestions, inquiries or any other feedback to [ROS@universal-robots.com](mailto:ROS@universal-robots.com).
```suggestion
Please give us feedback to [ROS@universal-robots.com](mailto:ROS@universal-robots.com) on what you have tested and how it worked out.
```

2021-02-25 11:46 UTC, merged