add reserve_ip
UniversalRobots/Universal_Robots_ROS_Driver pull request #350
Opened 2021-04-09 15:47 UTC by JS00000

This PR is copied from [here](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/pull/268), which can help the socket in the UR's Teach Pendant know the host IP address when this library is running in the Docker container (especially in Docker for Windows).

2021-05-03 20:59 UTC, gokul-gokz commented
I tested this PR on a ROS - melodic Docker image. Even-though, I was able to build the repository , I am unable to control the robot through the external control. After launching the driver, the following info was displayed on the terminal 
`Robot requested program.
Sent program to robot.
Robot ready to receive control commands.`
But when I try to set commands through moveit, the UR5 robot doesn't move and no response from the driver. Am i missing something?

2021-05-07 09:54 UTC, JS00000 commented
> I tested this PR on a ROS - melodic Docker image. Even-though, I was able to build the repository , I am unable to control the robot through the external control. After launching the driver, the following info was displayed on the terminal
> `Robot requested program. Sent program to robot. Robot ready to receive control commands.`
> But when I try to set commands through moveit, the UR5 robot doesn't move and no response from the driver. Am i missing something?

This PR need to build together with [this PR](https://github.com/UniversalRobots/Universal_Robots_Client_Library/pull/52). 
And when I was testing, moveit may fail to compute the trajectiry. Moveit run in Docker for Windows has some unknown issue. 
The specific reason needs more details.

2021-05-31 20:26 UTC, fmauch commented
https://github.com/UniversalRobots/Universal_Robots_Client_Library/pull/52 merged and binary release triggered. Waiting for binary release (melodic and noetic) before merging

2021-06-11 11:10 UTC, fmauch requested changes
Please see my comments below.

2021-06-11 11:10 UTC, fmauch commented on ur_robot_driver/src/hardware_interface.cpp
> +  robot_hw_nh.param<std::string>("reverse_ip", reverse_ip, "");
```suggestion
  std::string reverse_ip  robot_hw_nh.param<std::string>("reverse_ip", "");
```
This scheme is used everywhere around

2021-06-11 11:10 UTC, fmauch commented on ur_robot_driver/src/hardware_interface.cpp
> +                           (uint32_t)script_sender_port, servoj_gain, servoj_lookahead_time, non_blocking_read_, reverse_ip));
This line (this whole block) is not formatted properly. Please use clang-format to format this according to the style guidelines.

See https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/pull/350/checks?check_run_id=2762847292#step:3:511 for change required

2021-06-22 18:38 UTC, fmauch commented
Closing in favor of #412

2021-06-22 18:38 UTC, closed without merging